{{ $secrets := .Values.sync.secrets.secrets }}
{{ $vault := .Values.sync.secrets.keyvault_name}}
{{- if gt (len $secrets) 0 -}}
{{- range $secrets }}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync-{{.}}
spec:
  vault:
    name: {{ $vault }} # name of key vault
    object:
      contentType: application/x-yaml
      name: {{ . }} # name of the akv object
      type: multi-key-value-secret
  output:
    secret:
      name: {{ . }} # kubernetes secret name
---
{{- end }}
{{- end }}